version: '3.9'

services:
  vscode:
    build: 
      context: ./
      dockerfile: ./Dockerfile.dev
    command: /bin/bash -c "while sleep 1000; do :; done"
    container_name: api_vscode
    working_dir: /server
    networks:
      - app-network
    volumes:
      # Nous allons préciser le dossier local
      - .:/server:cached

  dbms:
    image: mariadb
    restart: always
    ports:
      - "3309:3306"
    env_file: 
      - ./dbms/.env.dev
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    volumes:
      - ./dbms/dbms-data:/var/lib/mysql
      - ./dbms/mariadb.cnf:/etc/mysql/mariadb.cnf
      # Pointer vers un dossier qui aura des scripts d'initialisation de notre base
      - ./dbms/dev-initdb.d:/docker-entrypoint-initdb.d
      # Ajouter le DDL qui va tourner en dernier
      - ./dbms/ddl/ddl.sql:/docker-entrypoint-initdb.d/999-ddl.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
